language: objective-c
os: osx
osx_image: xcode10.2
env:
  - TMP_DIR=./tmp  # For motion repo, so it doesn't attempt to use /tmp, to which it has no access
before_install:
  - wget https://s3.us-east-2.amazonaws.com/s3.rubymotion.com/RubyMotion-TravisCI.pkg
  - sudo installer -pkg RubyMotion-TravisCI.pkg -target /
  - eval "sudo motion activate $RUBYMOTION_LICENSE"
  - sudo motion update && motion repo
gemfile:
  - Gemfile
script: bundle exec rake spec
